matrix:
        include:
                - os: linux
                  dist: trusty
                  install:
                          - ./.travis/linux-ubuntu-trusty.install.sh

language: C
compiler: gcc

script: make test && sudo make install
